{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "7ac06477_7bd398d6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1322146
      },
      "writtenOn": "2021-02-22T02:43:32Z",
      "side": 1,
      "message": "thanks for the fix!. i didn\u0027t check but i suspect AttestationNoExternalServer also has the issue.",
      "revId": "10a1b581ec7bf008c718880beb6853b1c3f0ce43",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}