{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "06df5a4d_131513dd",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1309946
      },
      "writtenOn": "2021-01-29T08:10:38Z",
      "side": 1,
      "message": "This should help debug those \"Error starting the virtual machine\" failures, right now we don\u0027t have any view on the inside of the VM",
      "revId": "58e9350541712b2486f1a9e0b958143805787de0",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}