{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "18dcade4_59f01998",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1512627
      },
      "writtenOn": "2021-07-26T16:00:33Z",
      "side": 1,
      "message": "I\u0027m still getting a context canceled error when running this",
      "revId": "6215d454c7989fc5f487f9f5b9c8fdd7b1d04570",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}