{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "da1a7fec_9777200b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1447863
      },
      "writtenOn": "2022-03-10T22:40:06Z",
      "side": 1,
      "message": "There are a few failures in the bots. The new test passes on my VM. Are the bot failures unrelated?",
      "revId": "b834c6da1d4e1084df1bb273d66df483005f7e6c",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "40dbba91_3ca2726a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1349779
      },
      "writtenOn": "2022-03-14T09:02:27Z",
      "side": 1,
      "message": "Looks unrelated to me. Try to submit again, the bots may fail multiple times due to flakiness.",
      "parentUuid": "da1a7fec_9777200b",
      "revId": "b834c6da1d4e1084df1bb273d66df483005f7e6c",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}